"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./geometric/point");
var line_segment_1 = require("./geometric/line_segment");
var color_1 = require("./geometric/color");
var triangle_1 = require("./geometric/solid_shape/triangle");
var rectangle_1 = require("./geometric/solid_shape/rectangle");
var circle_1 = require("./geometric/solid_shape/circle");
var canvas_1 = require("./canvas");
point_1.testPointClass();
point_1.testCheckPointsForEqualityFunction();
line_segment_1.testClassLineSegment();
line_segment_1.testGetLengthBetweenPoints();
color_1.testGetColorNumberFromString();
color_1.testGetColorHexStringFromNumber();
triangle_1.testTriangleClass();
rectangle_1.testRectangleClass();
circle_1.testCircleClass();
canvas_1.testGetCoordinatesStrFromArr();
canvas_1.testClassCanvas();
